import React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

export const metadata: Metadata = {
  title: 'Daniel Batista | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <Header />
        <main className="flex flex-col items-center mx-auto gap-12 pb-20 max-w-7xl">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
